// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ugly.CodeGenerator.cxx
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CxxSerializationCode : CxxSerializationCodeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#include \"Serializer.h\"\r\n#include <cctype>\r\n#include <sstream>\r\n\r\nnamespace ugly\r" +
                    "\n{\r\n    namespace ");
            
            #line 12 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.Namespace)));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        void Serializer::IdMap::Clear()\r\n        {");
            
            #line 15 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

foreach (GameClass c in CxxHelper.Definition.Class.Values)
{
    if (c.HasId && !c.Id.Index)
    {
        
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 22 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(".clear();");
            
            #line 22 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n\r\n        namespace\r\n        {\r\n            template<typename T> voi" +
                    "d SerializeInternal(T& data, std::stringstream& buffer, Serializer::IdMap& ids, " +
                    "");
            
            #line 31 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 31 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerSetup)));
            
            #line default
            #line hidden
            this.Write("& playerSetup, ");
            
            #line 31 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, ");
            
            #line 31 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerState)));
            
            #line default
            #line hidden
            this.Write("& playerState);\r\n            ");
            
            #line 32 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

foreach (GameClass c in CxxHelper.Definition.Class.Values)
{
    
            
            #line default
            #line hidden
            this.Write("\r\n            template<> void SerializeInternal(");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& data, std::stringstream& buffer, Serializer::IdMap& ids, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerSetup)));
            
            #line default
            #line hidden
            this.Write("& playerSetup, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerState)));
            
            #line default
            #line hidden
            this.Write("& playerState);");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

}
            
foreach (GameClass c in CxxHelper.Definition.Class.Values)
{
    
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            template<> void SerializeInternal(");
            
            #line 45 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& data, std::stringstream& buffer, Serializer::IdMap& ids, ");
            
            #line 45 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 45 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerSetup)));
            
            #line default
            #line hidden
            this.Write("& playerSetup, ");
            
            #line 45 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, ");
            
            #line 45 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerState)));
            
            #line default
            #line hidden
            this.Write("& playerState)\r\n            {");
            
            #line 46 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

    if (c.HasId && !c.Id.Index)
    {
        
            
            #line default
            #line hidden
            this.Write("\r\n                ids.");
            
            #line 51 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("[data.");
            
            #line 51 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Id.Member[0])));
            
            #line default
            #line hidden
            this.Write("] = &data;");
            
            #line 51 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

    }
    foreach (ClassMember m in c.Member)
    {
        if ((c.HasId && c.Id.Index && c.Id.Member.Contains(m.Name)) || (m.Index == ClassMemberIndexType.MappedFromStrong))
        {
            continue;
        }
        
            
            #line default
            #line hidden
            this.Write("\r\n                {");
            
            #line 61 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

        if (m.Array != 0)
        {
            for (int i = 0; i < m.Array; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n                    int size");
            
            #line 68 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = (int)(");
            
            #line 68 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                if (i != 0)
                {
                    
            
            #line default
            #line hidden
            this.Write("size");
            
            #line 71 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i - 1));
            
            #line default
            #line hidden
            this.Write(" == 0 ? 0 : ");
            
            #line 71 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                
            
            #line default
            #line hidden
            this.Write("data.");
            
            #line 73 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 73 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                for (int j = 0; j < i; ++j)
                {
                    
            
            #line default
            #line hidden
            this.Write("[0]");
            
            #line 76 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(".size());\r\n                    buffer << size");
            
            #line 79 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" << \" \";");
            
            #line 79 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

            }
        }
        if (m.Condition != null && m.Condition.Type == ConditionType.While && m.Array != 0)
        {
            
            
            #line default
            #line hidden
            this.Write("                    bool executeLoop = true;");
            
            #line 85 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

        }
        string arrayIdxSuffix = "";
        for (int i = 0; i < m.Array; ++i)
        {
            
            
            #line default
            #line hidden
            this.Write("\r\n                    for (int idx");
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = 0; idx");
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" < size");
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("; ++idx");
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(")\r\n                    {");
            
            #line 93 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

            this.PushIndent("    ");
            arrayIdxSuffix += string.Format("[idx{0}]", i);
        }
        switch (CxxHelper.Definition.GetBasicType(m.Type))
        {
            case BasicType.Char:
            case BasicType.Enum:
                
            
            #line default
            #line hidden
            this.Write("                \r\n                    buffer << (int)data.");
            
            #line 103 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 103 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write(" << \" \";");
            
            #line 103 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                break;
            case BasicType.Class:
                if (m.Condition != null)
                {
                    
            
            #line default
            #line hidden
            this.Write("                    \r\n                    if (");
            
            #line 110 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    if (m.Condition.Type == ConditionType.While)
                    {
                        
            
            #line default
            #line hidden
            this.Write("(executeLoop = (executeLoop && ");
            
            #line 113 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write("data.");
            
            #line 115 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 115 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 115 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(m.Condition.Function)));
            
            #line default
            #line hidden
            this.Write("(gameSetup, playerSetup, gameState, playerState))");
            
            #line 115 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    if (m.Condition.Type == ConditionType.While)
                    {
                        
            
            #line default
            #line hidden
            this.Write("))");
            
            #line 118 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write("\r\n                    {");
            
            #line 122 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    this.PushIndent("    ");
                }
                if (m.Index == ClassMemberIndexType.RefId)
                {
                    GameClass mType = CxxHelper.Definition.Class[m.Type];
                    foreach (string mId in mType.Id.Member)
                    {
                        
            
            #line default
            #line hidden
            this.Write("\r\n                    if (data.");
            
            #line 132 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 132 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write(" == nullptr)\r\n                    {\r\n                        buffer << -1 << \" \";" +
                    "\r\n                    }\r\n                    else\r\n                    {");
            
            #line 137 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                        switch (CxxHelper.Definition.GetBasicType(mType.MemberMap[mId].Type))
                        {
                        case BasicType.Char:
                        case BasicType.Enum:
                            
            
            #line default
            #line hidden
            this.Write("                \r\n                        buffer << (int)data.");
            
            #line 144 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 144 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write("->");
            
            #line 144 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(mId)));
            
            #line default
            #line hidden
            this.Write(" << \" \";");
            
            #line 144 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                            break;
                        default:
                            
            
            #line default
            #line hidden
            this.Write("                \r\n                        buffer << data.");
            
            #line 149 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 149 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write("->");
            
            #line 149 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(mId)));
            
            #line default
            #line hidden
            this.Write(" << \" \";");
            
            #line 149 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                            break;
                            
                        }
                        
            
            #line default
            #line hidden
            this.Write("\r\n                    }");
            
            #line 155 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                }
                else
                {
                    
            
            #line default
            #line hidden
            this.Write("\r\n                    SerializeInternal(data.");
            
            #line 162 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 162 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write(", buffer, ids, gameSetup, playerSetup, gameState, playerState);");
            
            #line 162 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                if (m.Condition != null)
                {
                    this.PopIndent();
                    
            
            #line default
            #line hidden
            this.Write("\r\n                    }");
            
            #line 169 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                break;
            default:
                
            
            #line default
            #line hidden
            this.Write("\r\n                    buffer << data.");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arrayIdxSuffix));
            
            #line default
            #line hidden
            this.Write(" << \" \";");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                break;
        }
        for (int i = 0; i < m.Array; ++i)
        {
            this.PopIndent();
            
            
            #line default
            #line hidden
            this.Write("\r\n                    }");
            
            #line 183 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

        }
        
            
            #line default
            #line hidden
            this.Write("\r\n                }");
            
            #line 187 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

    }
    
            
            #line default
            #line hidden
            this.Write("\r\n            }");
            
            #line 191 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

}

this.PushIndent("            ");

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            this.Write(@"template<class T> T ReadNext(const char*& buf)
{
    std::uint64_t data = 0;
    bool negative = false;
    if (*buf == '-')
    {
        negative = true;
        ++buf;
    }
    while (std::isdigit(*buf))
    {
        data *= 10;
        data += ((*buf) - '0');
        ++buf;
    }
    if (*buf)
        ++buf;
    if (negative)
        return static_cast<T>(-static_cast<std::int64_t>(data));
    return static_cast<T>(data);
}

template<class T> void Deserialize(T& data, const char*& buf, ");
            
            #line 23 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("* gameSetup, ");
            
            #line 23 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("* gameState");
            
            #line 23 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

    if (CxxHelper.Server)
    {
        
            
            #line default
            #line hidden
            this.Write(", Serializer::IdMap* idSetup, , Serializer::IdMap* idState");
            
            #line 26 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
 
    }
    
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n    data = ReadNext<T>(buf);\r\n}");
            
            #line 31 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"


foreach (GameClass c in CxxHelper.Definition.Class.Values)
{
    
            
            #line default
            #line hidden
            this.Write("    \r\ntemplate<> void Deserialize(");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& data, const char*& buf, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("* gameSetup, ");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("* gameState");
            
            #line 37 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

    if (CxxHelper.Server)
    {
        
            
            #line default
            #line hidden
            this.Write(", Serializer::IdMap* idSetup, , Serializer::IdMap* idState");
            
            #line 40 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
 
    }
    
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 42 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

}
foreach (GameClass c in CxxHelper.Definition.Class.Values)
{
    
            
            #line default
            #line hidden
            this.Write("\r\n\r\ntemplate<> void Deserialize(");
            
            #line 49 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& data, const char*& buf, ");
            
            #line 49 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("* gameSetup, ");
            
            #line 49 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("* gameState");
            
            #line 49 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

    if (CxxHelper.Server)
    {
        
            
            #line default
            #line hidden
            this.Write(", Serializer::IdMap* idSetup, , Serializer::IdMap* idState");
            
            #line 52 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
 
    }
    
            
            #line default
            #line hidden
            this.Write(")\r\n{");
            
            #line 55 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

    foreach (ClassMember m in c.Member)
    {
        if (!CxxHelper.Server && ((c.HasId && c.Id.Index && c.Id.Member.Contains(m.Name)) || (m.Index == ClassMemberIndexType.MappedFromStrong)))
        {
            continue;
        }
        
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        auto& member = data.");
            
            #line 65 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 65 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"


        if (m.IsWeak && CxxHelper.Definition.Class[m.Type].Id.Index)
        {
            GameClass realType = CxxHelper.Definition.Class[m.Type];
            for (int i = 0; i < realType.Id.Member.Count; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        int classIdx");
            
            #line 74 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<int>();");
            
            #line 74 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            if (CxxHelper.Server)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        if (classIdx0 >= 0");
            
            #line 80 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                for (int i = 1; i < realType.Id.Member.Count; ++i)
                {
                    
            
            #line default
            #line hidden
            this.Write(" && classIdx");
            
            #line 83 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" >= 0");
            
            #line 83 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                }
                for (int i = 0; i < realType.Id.Member.Count; ++i)
                {
                    
            
            #line default
            #line hidden
            this.Write(" && ");
            
            #line 87 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(realType.Id.Source.FormatMapping(Case.LowerCamelCase, null, "(*gameSetup)", "(*gameState)")));
            
            #line default
            #line hidden
            
            #line 87 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                    for (int j = 0; j < i; ++j)
                    {
                        
            
            #line default
            #line hidden
            this.Write("[classIdx");
            
            #line 90 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 90 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write(".size() > classIdx");
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            
            #line 92 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 94 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            else
            {
                
            
            #line default
            #line hidden
            this.Write("                            \r\n        if (classIdx0 != -1)");
            
            #line 100 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            member = &");
            
            #line 105 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(realType.Id.Source.FormatMapping(Case.LowerCamelCase, null, "(*gameSetup)", "(*gameState)")));
            
            #line default
            #line hidden
            
            #line 105 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            for (int i = 0; i < c.Id.Member.Count; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("[classIdx");
            
            #line 108 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 108 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            
            
            #line default
            #line hidden
            this.Write(";\r\n        }");
            
            #line 111 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

        }
        else if (m.IsWeak && !c.Id.Index && CxxHelper.Server)
        {
            
            
            #line default
            #line hidden
            this.Write("        {\r\n            int classIdx = ReadNext<int>(buf);\r\n            member = n" +
                    "ullptr;\r\n            if (idState != nullptr)\r\n            {\r\n                aut" +
                    "o classIt = idState->");
            
            #line 121 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Type)));
            
            #line default
            #line hidden
            this.Write(".find(classIdx);\r\n                if (classIt != idState->");
            
            #line 122 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Type)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                {\r\n                    member = classIt->second;\r\n      " +
                    "          }\r\n            }\r\n            if (member == nullptr && idSetup != null" +
                    "ptr)\r\n            {\r\n                auto classIt = idSetup->");
            
            #line 129 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Type)));
            
            #line default
            #line hidden
            this.Write(".find(classIdx);\r\n                if (classIt != idSetup->");
            
            #line 130 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(m.Type)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                {\r\n                    member = classIt->second;\r\n      " +
                    "          }\r\n            }\r\n        }");
            
            #line 135 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

        }
        else
        {
            for (int i = 0; i < m.Array; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        int size");
            
            #line 143 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<int>(buf);");
            
            #line 143 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            if (m.Array != 0)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        auto& array0 = member;\r\n        array0.resize(size0);");
            
            #line 150 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            for (int i = 1; i < m.Array; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        for (int idx");
            
            #line 156 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i - 1));
            
            #line default
            #line hidden
            this.Write(" = 0; i < size");
            
            #line 156 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i - 1));
            
            #line default
            #line hidden
            this.Write("; ++i)\r\n        {\r\n            auto& array");
            
            #line 158 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = array");
            
            #line 158 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i - 1));
            
            #line default
            #line hidden
            this.Write("[idx");
            
            #line 158 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i - 1));
            
            #line default
            #line hidden
            this.Write("];\r\n            array");
            
            #line 159 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(".resize(size");
            
            #line 159 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 159 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                this.PushIndent("    ");
            }
            for (int i = 1; i < m.Array; ++i)
            {
                this.PopIndent();
                
            
            #line default
            #line hidden
            this.Write("\r\n        }");
            
            #line 167 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            for (int i = 0; i < m.Array; ++i)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n        for (int idx");
            
            #line 173 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = 0; idx");
            
            #line 173 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" < size");
            
            #line 173 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("; ++idx");
            
            #line 173 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            auto& array");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(" = array");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("[idx");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("];");
            
            #line 175 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                this.PushIndent("    ");
            }
            if (m.Array != 0)
            {
            
            
            #line default
            #line hidden
            this.Write("\r\n        Deserialize(array");
            
            #line 182 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m.Array));
            
            #line default
            #line hidden
            this.Write(", buf, gameSetup, gameState");
            
            #line 182 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                if (CxxHelper.Server)
                {
                    
            
            #line default
            #line hidden
            this.Write(", idSetup, idState");
            
            #line 185 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 187 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                if (m.Index == ClassMemberIndexType.Strong)
                {
                    GameClass mType = CxxHelper.Definition.Class[m.Type];
                    if (mType.HasId && mType.Id.Index)
                    {
                        for (int i = 0; i < mType.Id.Member.Count; ++i)
                        {
                            
            
            #line default
            #line hidden
            this.Write("\r\n        array");
            
            #line 197 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m.Array));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 197 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(mType.Id.Member[i])));
            
            #line default
            #line hidden
            this.Write(" = idx");
            
            #line 197 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 197 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                        }
                        foreach (IndexMapping mapping in mType.IndexMapping)
                        {
                            
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 203 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mapping.FormatMapping(Case.LowerCamelCase, string.Format("array{0}", m.Array), "(*gameSetup)", "(*gameState)")));
            
            #line default
            #line hidden
            
            #line 203 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                            if (m.Array == 0)
                            {
                                
            
            #line default
            #line hidden
            this.Write(" = &array");
            
            #line 206 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m.Array));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 206 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                            }
                            else if (m.Array == 1)
                            {
                                
            
            #line default
            #line hidden
            this.Write(".push_back(&array");
            
            #line 210 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m.Array));
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 210 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                            }
                            else
                            {
                                throw new Exception("Unsupported arity > 1 for mapping");
                            }
                        }
                    }
                }
            }
            else
            {
            
            
            #line default
            #line hidden
            this.Write("\r\n        Deserialize(member, buf, gameSetup, gameState");
            
            #line 224 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                if (CxxHelper.Server)
                {
                    
            
            #line default
            #line hidden
            this.Write(", idSetup, idState");
            
            #line 227 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 229 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
            for (int i = 0; i < m.Array; ++i)
            {
                this.PopIndent();
            
            
            #line default
            #line hidden
            this.Write("\r\n        }");
            
            #line 236 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

            }
        }
        
            
            #line default
            #line hidden
            this.Write("\r\n    }");
            
            #line 241 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

    }
    
            
            #line default
            #line hidden
            this.Write("\r\n}");
            
            #line 245 "D:\ugly\CodeGenerator\cxx\CxxDeserializerInc.tt"

        
}

            
            #line default
            #line hidden
            
            #line 198 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

this.PopIndent();

            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n        \r\n        std::string Serializer::SerializeSetup(");
            
            #line 204 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 204 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerSetup)));
            
            #line default
            #line hidden
            this.Write("& playerSetup, ");
            
            #line 204 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, ");
            
            #line 204 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerState)));
            
            #line default
            #line hidden
            this.Write(@"& playerState)
        {
            std::stringstream buffer;
            gameSetupId.Clear();
            buffer << playerSetup.id << '\n';
            SerializeInternal(gameSetup, buffer, gameSetupId, gameSetup, playerSetup, gameState, playerState);
            buffer << '\n';
            return buffer.str();
        }

        std::string Serializer::SerializeState(");
            
            #line 214 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 214 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerSetup)));
            
            #line default
            #line hidden
            this.Write("& playerSetup, ");
            
            #line 214 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, ");
            
            #line 214 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.PlayerState)));
            
            #line default
            #line hidden
            this.Write(@"& playerState)
        {
            std::stringstream buffer;
            gameStateId.Clear();
            SerializeInternal(gameState, buffer, gameStateId, gameSetup, playerSetup, gameState, playerState);
            buffer << '\n';
            return buffer.str();
        }

        bool Serializer::ExecuteOrder(const std::string& order, ");
            
            #line 223 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameSetup)));
            
            #line default
            #line hidden
            this.Write("& gameSetup, ");
            
            #line 223 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(CxxHelper.Definition.Config.GameState)));
            
            #line default
            #line hidden
            this.Write("& gameState, int currentPlayerId)\r\n        {\r\n            const char* buf = order" +
                    ".c_str();\r\n            int _methodId = ReadNext<int>(buf);\r\n            switch (" +
                    "_methodId)\r\n            {");
            
            #line 228 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

    foreach (GameFile f in CxxHelper.Definition.Files)
    {
        foreach (GameClass c in f.Class)
        {
            foreach (ClassMethod m in c.Method)
            {
                
            
            #line default
            #line hidden
            this.Write("\r\n                case ");
            
            #line 237 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m.MethodId));
            
            #line default
            #line hidden
            this.Write(": // ");
            
            #line 237 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("::");
            
            #line 237 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            this.Write("\r\n                {");
            
            #line 238 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                if (c.Id.Index)
                {
                    
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 243 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(" argThisTmp;");
            
            #line 243 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    foreach (string mId in c.Id.Member)
                    {
                        
            
            #line default
            #line hidden
            this.Write("\r\n                    argThisTmp.");
            
            #line 248 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(mId)));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<");
            
            #line 248 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(c.MemberMap[mId].Type))));
            
            #line default
            #line hidden
            this.Write(">(buf);");
            
            #line 248 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                    
            
            #line default
            #line hidden
            this.Write("                    \r\n                    ");
            
            #line 252 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& argThis = ");
            
            #line 252 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Id.Source.FormatMapping(Case.LowerCamelCase, "argThisTmp", "gameSetup", "gameState")));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 252 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                else
                {
                    
            
            #line default
            #line hidden
            this.Write("                    \r\n                    ");
            
            #line 258 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(c.MemberMap[c.Id.Member[0]].Type))));
            
            #line default
            #line hidden
            this.Write(" argThisId = ReadNext<");
            
            #line 258 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(c.MemberMap[c.Id.Member[0]].Type))));
            
            #line default
            #line hidden
            this.Write(">(buf);\r\n                    auto argThisIt = gameStateId.");
            
            #line 259 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(".find(argThisId);\r\n                    if (argThisIt == gameStateId.");
            
            #line 260 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                    {\r\n                        argThisIt = gameSetupId.");
            
            #line 262 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(".find(argThisId);\r\n                        if (argThisIt == gameSetupId.");
            
            #line 263 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                            return false;\r\n                    }\r\n      " +
                    "              ");
            
            #line 266 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(c.Name)));
            
            #line default
            #line hidden
            this.Write("& argThis = *(argThisIt->second);");
            
            #line 266 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                foreach (MethodParam a in m.Param)
                {
                    BasicType type = CxxHelper.Definition.GetBasicType(a.Type);
                    if (type == BasicType.Class)
                    {
                        GameClass aType = CxxHelper.Definition.Class[a.Type];
                        if (!aType.HasId)
                        {
                            
            
            #line default
            #line hidden
            this.Write("                            \r\n                    ");
            
            #line 278 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 278 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(";\r\n                    Deserialize(");
            
            #line 279 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(", &gameSetup, &gameState, &gameSetupId, &gameStateId);");
            
            #line 279 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                        }
                        else if (aType.Id.Index)
                        {
                            
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 285 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 285 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_tmp;");
            
            #line 285 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                            foreach (string mId in aType.Id.Member)
                            {
                                
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 290 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_tmp.");
            
            #line 290 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(mId)));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<");
            
            #line 290 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(c.MemberMap[mId].Type))));
            
            #line default
            #line hidden
            this.Write(">(buf);");
            
            #line 290 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                            }
                            
            
            #line default
            #line hidden
            this.Write("                    \r\n                    ");
            
            #line 294 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write("& ");
            
            #line 294 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 294 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Id.Source.FormatMapping(Case.LowerCamelCase, string.Format("{0}_tmp", Case.LowerCamelCase.Convert(a.Name)), "gameSetup", "gameState")));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 294 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            this.Write("                    \r\n                    ");
            
            #line 300 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(aType.MemberMap[aType.Id.Member[0]].Type))));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 300 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_id = ReadNext<");
            
            #line 300 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(CxxHelper.Definition.GetBasicType(aType.MemberMap[aType.Id.Member[0]].Type))));
            
            #line default
            #line hidden
            this.Write(">(buf);\r\n                    auto ");
            
            #line 301 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_it = gameStateId.");
            
            #line 301 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(".find(");
            
            #line 301 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_id);\r\n                    if (");
            
            #line 302 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_it == gameStateId.");
            
            #line 302 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                    {\r\n                        ");
            
            #line 304 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_it = gameSetupId.");
            
            #line 304 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(".find(");
            
            #line 304 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_id);\r\n                        if (");
            
            #line 305 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_it == gameSetupId.");
            
            #line 305 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(".end())\r\n                            return false;\r\n                    }\r\n      " +
                    "              ");
            
            #line 308 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write("& ");
            
            #line 308 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(" = *(");
            
            #line 308 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write("_it->second);");
            
            #line 308 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                        }
                    }
                    else if (type == BasicType.Enum)
                    {
                        
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 315 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 315 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<");
            
            #line 315 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(a.Type)));
            
            #line default
            #line hidden
            this.Write(">(buf);");
            
            #line 315 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            this.Write("\r\n                    ");
            
            #line 321 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(type)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 321 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            this.Write(" = ReadNext<");
            
            #line 321 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CxxHelper.GetBasicTypeName(type)));
            
            #line default
            #line hidden
            this.Write(">(buf);");
            
            #line 321 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                    }
                }
                
            
            #line default
            #line hidden
            this.Write("\r\n                    return argThis.");
            
            #line 326 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.CamelCase.Convert(m.Name)));
            
            #line default
            #line hidden
            this.Write("(gameSetup, gameSetup.player[currentPlayerId], gameState, gameState.player[curren" +
                    "tPlayerId]");
            
            #line 326 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                foreach (MethodParam a in m.Param)
                {
                    
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 329 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Case.LowerCamelCase.Convert(a.Name)));
            
            #line default
            #line hidden
            
            #line 329 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

                }
                
            
            #line default
            #line hidden
            this.Write(");\r\n                }");
            
            #line 332 "D:\ugly\CodeGenerator\cxx\CxxSerializationCode.tt"

            }
        }
    }
            
            #line default
            #line hidden
            this.Write("\r\n                default:\r\n                    return false;\r\n            }\r\n   " +
                    "     }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class CxxSerializationCodeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
